# cspell:word lycheeverse
---
env:
  NODE_VERSION: '25'
jobs:
  build-docs:
    name: 'Build docs'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v6'
    - uses: 'actions/setup-node@v6'
      with:
        cache: 'npm'
        cache-dependency-path: 'docs/package-lock.json'
        node-version: '${{ env.NODE_VERSION }}'
    - run: 'npm ci'
      working-directory: 'docs'
    - run: 'npx vitepress build'
      working-directory: 'docs'
    - uses: 'lycheeverse/lychee-action@v2'
      with:
        args: >-
          --config cfg/lychee.toml
          --include-fragments
          --root-dir docs/.vitepress/dist
          docs/.vitepress/dist/**/*.html
name: 'Build docs'
'on':
  pull_request: null
...
